Request to merge Jest testing
Georjane/react-calculator pull request #7
Opened 2021-07-11 04:52 UTC by Georjane

Setup tests for the project.
- Add unit tests for your calculate.js file.
- Make sure that all elements are displayed at Home page, Calculator page, Quote page

2021-07-12 01:13 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUIRED🛑️🛑️🛑️**

Hello @Georjane 
Great work on this milestone.
This is impressive work👏️👏️

However, let's make some improvements and get it approved.

[REQUIRED]: there are snapshot tests that are checking if the main components, at least Home, Calculator, and Quote, from Math Magicians mockups are displayed.
[REQUIRED]: Add negative test cases.
[REQUIRED]: Write test cases every function in the app.

That's it.
Make the required changes and get it approved👍️👍️.
Happy coding💻️💻️

2021-07-13 08:54 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

Hi @Georjane, great effort implementing some of the changes by the previous TSE. However, a few improvements need to be made to make your project stand out and look more professional, and have this project approved. Check my comments below ⬇️ 

*All the best, you are doing an awesome job, keep up the good work*

### *Request another code review after applying the changes*

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-13 08:54 UTC, Elbie-em commented on src/_tests_/__snapshots__/snapshots.test.js.snap
> +`;
- [ ] You should create separate snapshots for your integration testing other than mixing them all in one file. This makes your project look more professional with clean with readable code. e.g for the home component you can have the snapshot in `home.test.js.snap`.

2021-07-13 08:54 UTC, Elbie-em commented on src/_tests_/snapshots.test.js
> +});
- [ ] Kindly add tests for your snapshots in different test files e.g home component to be tested in `home.test.js`

2021-07-13 08:54 UTC, Elbie-em commented on src/_tests_/app.test.js
> +});
- [ ] There is a mixture of integration and unit testing in this file, create `calculate.test.js ` to test all functions of your calculator and move the integration testing units to their respective files, do not forget to add negative tests for your cases.

2021-07-14 11:27 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED👍️👍️👍️👍️**

Hello @Georjane 
Great work making the requested changes.👏️👏️

You can merge👍️👍️

Happy coding💻️💻️💻️

2021-07-14 11:38 UTC, merged